import React from "react"
import { LoginScreen } from "./login-screen"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  LoginScreen,
  "https://www.figma.com/design/gcz1z0827AM5nz6Ise741e/Simple-Design-System--Community-?node-id=4039%3A12329",
  {
    props: {},
    example: (props) => <LoginScreen />,
  },
)
