import React from "react"
import { LogoutButton } from "./logout-button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  LogoutButton,
  "https://www.figma.com/design/gcz1z0827AM5nz6Ise741e/Simple-Design-System--Community-?node-id=4039%3A12325",
  {
    props: {},
    example: (props) => <LogoutButton />,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  LogoutButton,
  "https://www.figma.com/design/gcz1z0827AM5nz6Ise741e/Simple-Design-System--Community-?node-id=4185%3A3778",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "iconEnd": figma.instance('Icon End'),
      // "hasIconEnd": figma.boolean('Has Icon End'),
      // "hasIconStart": figma.boolean('Has Icon Start'),
      // "iconStart": figma.instance('Icon Start'),
      // "variant": figma.enum('Variant', {
      //   "Primary": "primary",
      //   "Neutral": "neutral",
      //   "Subtle": "subtle"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Disabled": "disabled"
      // }),
      // "size": figma.enum('Size', {
      //   "Medium": "medium",
      //   "Small": "small"
      // })
    },
    example: (props) => <LogoutButton />,
  },
)
