import React from "react"
import { TeamSettings } from "./team-settings"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TeamSettings,
  "https://www.figma.com/design/gcz1z0827AM5nz6Ise741e/Simple-Design-System--Community-?node-id=4039%3A12955",
  {
    props: {},
    example: () => (
      <TeamSettings
        currentTeam={{
          ok: true,
          team: {
            id: "team-1",
            slug: "ai-craft",
            name: "AI-Craft",
            status: "active",
            settings: {}
          },
          defaults: {
            version: 1,
            defaults: {
              general: {
                name: "Общий",
                slug: "general"
              }
            },
            mediaSources: {},
            updatedAt: "2026-03-19T00:00:00.000Z"
          }
        }}
        teamMembers={{
          ok: true,
          team: {
            id: "team-1",
            slug: "ai-craft",
            name: "AI-Craft",
            status: "active"
          },
          users: [
            {
              id: "user-1",
              email: "lead@example.com",
              displayName: "Lead User",
              role: "lead",
              status: "active"
            },
            {
              id: "user-2",
              email: "editor@example.com",
              displayName: "Editor User",
              role: "editor",
              status: "active"
            }
          ]
        }}
        canManageMembers={true}
      />
    ),
  },
)
