openapi: 3.0.0
info:
  title: AI-Craft Web Proxy Gateway
  version: 1.0.0

paths:
  /:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bbatcmo4t42t8vmcrqka
        service_account_id: ajeirckda2gk7b15rqa0
      responses:
        '200':
          description: Proxied response

  /{proxy+}:
    parameters:
      - explode: false
        in: path
        name: proxy
        required: false
        schema:
          default: '-'
          type: string
        style: simple
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bbatcmo4t42t8vmcrqka
        service_account_id: ajeirckda2gk7b15rqa0
      responses:
        '200':
          description: Proxied response
